mongo:
  build: ./mongo
  volumes:
    - /data/db:/data/db
  ports:
    - "27017:27017"
cb_recommender:
  build: ./cb_recommender
  command: python ./cb_recommender recommender.py
  # volumes:
  #   - .:/code
  # ports:
  #   - "8000:8000"
  links:
    - mongo

